// examples/react/src/App.jsx
import React, {useState} from 'react'
import LazyList from 'lazy-load-list/react'
import Github from './components/Github'
import colors from './colors'

function App() {

  const [copied, setCopied] = useState('')

  const copyColor = (color) => {
    window.navigator.clipboard.writeText(color)
    showCopiedText(color)
  }
  
  const showCopiedText = (color) => {
    setCopied(color)
    setTimeout(() => {
      setCopied('')
    }, 800);
  }

  const renderItem = ({item, index}) => (
    <div key={index} onClick={()=>copyColor(item.hex)} className="item" style={{backgroundColor: item.hex}}>
      <div className="copy">{ item.hex }</div>
    </div>
  )
  return (
    <>
      <Github />
      <main>
        
        <h1>
          Random 500 Colors
        </h1>
        
        <h4>
          example for <a href="https://github.com/omer73364/lazy-load-list" target="blank">lazy load list</a> on React js
        </h4>

        {
          copied ?
          <h4 className="cpoied">
            { `Color ${copied} copied to clipboard` }
          </h4> : null
        }
        
        <div className="container">
          <LazyList
            data={colors}
            itemsPerRender={15}
            containerClasses="list"
            defaultLoadingColor="#222"
            renderItem={renderItem}
          />
        </div>

      </main>
    </>
  )
}

export default App

// examples/svelte/src/App.svelte
<script>
  import LazyList from 'lazy-load-list/svelte'
  import Github from './Components/Github.svelte';
  import './index.css'
  import colors from './colors'
  
  let copied = ''

  const copyColor = (color) => {
    window.navigator.clipboard.writeText(color)
    showCopiedText(color)
  }

  const showCopiedText = (color) => {
    copied = color
    setTimeout(() => {
      copied = ''
    }, 800);
  }

</script>

<Github/>
<main>
    
  <h1>
    Random 500 Colors
  </h1>
  
  <h4>
    example for <a href="https://github.com/omer73364/lazy-load-list" target="blank">lazy load list</a> on Svelte js
  </h4>

  {#if copied}
  <h4 class="cpoied">
    { `Color ${copied} copied to clipboard` }
  </h4>
  {/if}
  
  <div class="container">
    <LazyList
      data={colors}
      itemsPerRender={15}
      containerClasses="list"
      defaultLoadingColor="#222"
      let:item={item}
    >
      <div on:click={()=>copyColor(item?.hex)} class="item" style={`background-color: ${item?.hex}`}>
        <div class="copy">{ item?.hex }</div>
      </div>
    </LazyList>
  </div>

</main>
